# CMake generated Testfile for 
# Source directory: /Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal
# Build directory: /Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(compilation_of__cgal_periodic2D "/opt/local/bin/cmake" "--build" "/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal" "--target" "cgal_periodic2D")
set_tests_properties(compilation_of__cgal_periodic2D PROPERTIES  FIXTURES_SETUP "cgal_periodic2D" LABELS "Mobile" _BACKTRACE_TRIPLES "/opt/local/share/CGAL/cmake/CGAL_add_test.cmake;88;add_test;/opt/local/share/CGAL/cmake/CGAL_add_test.cmake;183;cgal_add_compilation_test;/opt/local/share/CGAL/cmake/CGAL_CreateSingleSourceCGALProgram.cmake;63;cgal_add_test;/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal/CMakeLists.txt;40;create_single_source_cgal_program;/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal/CMakeLists.txt;0;")
add_test(execution___of__cgal_periodic2D "/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal/cgal_periodic2D")
set_tests_properties(execution___of__cgal_periodic2D PROPERTIES  DEPENDS "compilation_of__cgal_periodic2D" FIXTURES_REQUIRED "Mobile;cgal_periodic2D" LABELS "Mobile" WORKING_DIRECTORY "/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal/__exec_test_dir" _BACKTRACE_TRIPLES "/opt/local/share/CGAL/cmake/CGAL_add_test.cmake;242;add_test;/opt/local/share/CGAL/cmake/CGAL_CreateSingleSourceCGALProgram.cmake;63;cgal_add_test;/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal/CMakeLists.txt;40;create_single_source_cgal_program;/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal/CMakeLists.txt;0;")
add_test(Mobile_SetupFixture "/opt/local/bin/cmake" "-E" "copy_directory" "/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal" "/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal/__exec_test_dir")
set_tests_properties(Mobile_SetupFixture PROPERTIES  FIXTURES_SETUP "Mobile" LABELS "Mobile" _BACKTRACE_TRIPLES "/opt/local/share/CGAL/cmake/CGAL_add_test.cmake;128;add_test;/opt/local/share/CGAL/cmake/CGAL_add_test.cmake;245;cgal_setup_test_properties;/opt/local/share/CGAL/cmake/CGAL_CreateSingleSourceCGALProgram.cmake;63;cgal_add_test;/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal/CMakeLists.txt;40;create_single_source_cgal_program;/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal/CMakeLists.txt;0;")
add_test(Mobile_CleanupFixture "/opt/local/bin/cmake" "-E" "remove_directory" "/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal/__exec_test_dir")
set_tests_properties(Mobile_CleanupFixture PROPERTIES  FIXTURES_CLEANUP "Mobile" LABELS "Mobile" _BACKTRACE_TRIPLES "/opt/local/share/CGAL/cmake/CGAL_add_test.cmake;145;add_test;/opt/local/share/CGAL/cmake/CGAL_add_test.cmake;245;cgal_setup_test_properties;/opt/local/share/CGAL/cmake/CGAL_CreateSingleSourceCGALProgram.cmake;63;cgal_add_test;/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal/CMakeLists.txt;40;create_single_source_cgal_program;/Users/benmorton/Library/Mobile Documents/com~apple~CloudDocs/rdsolver/rd/triangulation/cgal/CMakeLists.txt;0;")
